DEFAULT_PARSER = "stelton_2025"
TARGET_CURRENCY = "EUR"
CURRENCY_AUTO_MIN_RATIO = 0.6
CURRENCY_AUTO_MIN_COUNT = 5
CONFIDENCE_THRESHOLD = 0.75
OCR_CONFIDENCE_PENALTY = 0.15
THRESHOLD_TEXT_LEN_FOR_OCR = 40
OCR_TEXT_MIN_CHARS = THRESHOLD_TEXT_LEN_FOR_OCR
PRICE_MIN = 0.01
PRICE_MAX = 1_000_000
REVIEW_RATE_THRESHOLD = 0.15
DEBUG_JSON_SUFFIX = ".debug.json"
DEBUG_JSON_DEFAULT = False
DEBUG_JSON_ALWAYS_ON_FAILED = True
APP_VERSION = "dev"
INPUT_DIR = "input"
OUTPUT_DIR = "output"
DEBUG_PACK_DIR = "output/debug"
CACHE_DIR = "output/cache"
CACHE_ENABLED = True
CACHE_VERSION = "v1"
CACHE_EARLY_STOP_MIN_PAGES = 8
CACHE_EARLY_STOP_SCORE = 12.0
CACHE_EARLY_STOP_STRONG_PAGES = 4
CACHE_SAMPLE_COUNT_CAP = 200
CACHE_SAMPLE_RETRY_MULTIPLIER = 2.0
CACHE_SAMPLE_SWEEP_MULTIPLIER = 2.0
CACHE_WORDS_TOP_M = 16
CACHE_TABLE_LIKELIHOOD_WEIGHT = 1.0
CACHE_OCR_MAX_PAGES = 30
CACHE_SWEEP_TARGET_PAGES = 40
CACHE_SWEEP_STEP_MIN = 10
CACHE_SWEEP_EXPAND_PAGES = 2
CACHE_SWEEP_HIT_SCORE = 10.0
CACHE_STOPWORD_PENALTY = 0.2
CACHE_LEGAL_PENALTY = 0.4
CACHE_ENABLE_SWEEP_AFTER_RETRY = True
CACHE_LEGAL_MARKERS = [
    "terms",
    "conditions",
    "cgv",
    "condizioni generali",
    "decreto",
    "direttiva",
    "codice civile",
    "governing law",
    "jurisdiction",
]
LABEL_DICTIONARY_PATH = "profiles/label_dictionary.json"
PROFILES_DIR = "profiles"

TRIAGE_TEXT_LEN_MIN = 80
TRIAGE_SAMPLE_PAGES_MAX = 20
TRIAGE_TOP_K_MIN = 8
TRIAGE_TOP_K_MAX = 20
TRIAGE_STOPWORDS = [
    "terms",
    "conditions",
    "indice",
    "index",
    "contents",
    "table of contents",
]
TRIAGE_TABLE_X_BIN_SIZE = 20
TRIAGE_TABLE_Y_BIN_SIZE = 5
TRIAGE_TABLE_MIN_COLUMNS = 3
TRIAGE_TABLE_MIN_BIN_HITS = 10
TRIAGE_MARKER_SCORE_MIN = 6
TRIAGE_TABLE_SCORE_MIN = 6.0
TRIAGE_CODE_PRICE_SCORE_MIN = 6
TRIAGE_PRICE_MIN_COUNT = 3
TRIAGE_MARKER_MIN_COUNT = 2
TRIAGE_TABLE_NUMERIC_RATIO_MIN_FOR_OK = 0.2
TRIAGE_PRICE_SIGNAL_MIN_FOR_OK = 1
AUTO_ROWS_MIN = 5
AUTO_UNIQUE_CODE_RATIO_MIN = 0.15
AUTO_KEY_FIELDS_RATE_MIN = 0.5
AUTO_EXCELLENT_KEY_FIELDS_RATE_MIN = 0.8
AUTO_EXCELLENT_REVIEW_RATE_MAX = 0.2
AUTO_SCORE_WEIGHT_KEY_FIELDS = 1.0
AUTO_SCORE_WEIGHT_UNIQUE = 0.6
AUTO_SCORE_WEIGHT_REVIEW = 0.5
AUTO_SCORE_WEIGHT_DUP_CONFLICT = 0.8
AUTO_MAX_SECONDS_PER_PARSER_EVAL = 10
AUTO_EARLY_DISCARD_FACTOR = 0.5
TABLE_WORDS_HINT_MIN_RATIO = 0.2
TABLE_WORDS_HINT_MIN_SPACE_RATIO = 0.3
CODE_MIN_LEN = 5
